---
.gitattributes:
  # As this is for Windows, ERB files can be either LF or CRLF
  exclude:
  - "*.erb"

.gitignore:
  required:
    - ---.project

.gitlab-ci.yml:
  unmanaged: true

.travis.yml:
  unmanaged: true

.rubocop.yml:
  default_configs:
    inherit_from: .rubocop_todo.yml
    require:
    - rubocop-rspec

appveyor.yml:
  unmanaged: true

Gemfile:
  required:
    ':system_tests':
      - gem: 'nokogiri'
        platforms:
          - ruby
          - mswin
          - mingw
          - x64_mingw

spec/default_facts.yml:
  unmanaged: true

Rakefile:
  unmanaged: true

spec/spec_helper.rb:
  mock_with: ':rspec'
  coverage_report: true
