---
version: 1.1.x.{build}
branches:
  only:
    - appveyor-test
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
  - SET
  - 'mkdir C:\ProgramData\PuppetLabs\code && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
environment:
  SIMPLECOV: yes
  matrix:
    -
      RUBY_VERSION: 24-x64
      CHECK: syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24-x64
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25-x64
      CHECK: parallel_spec
    -
      RUBY_VERSION: 25-x64
      ACCEPTANCE: yes
      TARGET_HOST: localhost
    -
      RUBY_VERSION: 25-x64
      ACCEPTANCE: yes
      TARGET_HOST: localhost
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
for:
-
  matrix:
    only:
      - ACCEPTANCE: yes
  install:
    - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
    - ps: |
        if($env:APPVEYOR_SCHEDULED_BUILD -eq "true") {
          if($PUPPET_GEM_VERSION -eq '~> 5.0') {
            $collection = 'puppet5-nightly'
          }
          else {
             $collection = 'puppet6-nightly'
          }

          $source = "http://nightlies.puppet.com/downloads/gems/$collection/puppet-latest-x64-mingw32.gem"
          $local_gems_location = "vendor\gems"

          Invoke-WebRequest $source -OutFile "puppet.gem"

          New-Item -ItemType Directory -Force -Path $local_gems_location
          gem unpack puppet.gem --target $local_gems_location

          $puppet_gem_version = (cat "$local_gems_location\puppet\lib\puppet\version.rb" | where { $_ -imatch " PUPPETVERSION"}).Split("=")[1].Trim(' ', "'")

          $env:PUPPET_GEM_PATH = "file://$pwd\$local_gems_location\puppet"
          $env:PUPPET_GEM_VERSION = $puppet_gem_version
        }
    - bundle install --jobs 4 --retry 2
    - type Gemfile.lock
  test_script:
    - bundle exec puppet -V
    - ruby -v
    - gem -v
    - bundle -v
    - bundle exec rake spec_prep
    - bundle exec rake litmus:acceptance:localhost
matrix:
  fast_finish: true
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install --jobs 4 --retry 2 --without system_tests
  - type Gemfile.lock
build: off
test_script:
  - bundle exec puppet -V
  - ruby -v
  - gem -v
  - bundle -v
  - bundle exec rake %CHECK%
notifications:
  - provider: Email
    to:
      - nobody@nowhere.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
